#!/bin/bash

/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Very Fast 1080p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Very-Fast-1080p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Fast 1080p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Fast-1080p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Very Fast 720p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Very-Fast-720p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Fast 720p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Fast-720p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "HQ 1080p30 Surround" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-HQ-1080p30-Surround.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "HQ 720p30 Surround" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-HQ-720p30-Surround.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Super HQ 1080p30 Surround" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Super-HQ-1080p30-Surround.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Super HQ 720p30 Surround" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Super-HQ-720p30-Surround.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Discord Nitro Large 3-6 Minutes 1080p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Discord-Nitro-Large-3-6-Minutes-1080p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Discord Nitro Medium 5-10 Minutes 720p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Discord-Nitro-Medium-5-10-Minutes-720p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Vimeo YouTube HQ 1440p60 2.5K" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Vimeo-YouTube-HQ-1440p60-2.5K.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Vimeo YouTube HQ 1080p60" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Vimeo-YouTube-HQ-1080p60.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Vimeo YouTube HQ 720p60" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Vimeo-YouTube-HQ-720p60.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Vimeo YouTube 720p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Vimeo-YouTube-720p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Amazon Fire 1080p30 Surround" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Amazon-Fire-1080p30-Surround.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Apple 1080p30 Surround" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Apple-1080p30-Surround.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "H.265 MKV 1080p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-H.265-MKV-1080p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "H.265 MKV 720p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-H.265-MKV-720p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "H.264 MKV 1080p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-H.264-MKV-1080p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "H.264 MKV 720p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-H.264-MKV-720p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "VP9 MKV 1080p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-VP9-MKV-1080p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "VP9 MKV 720p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-VP9-MKV-720p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "VP8 MKV 1080p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-VP8-MKV-1080p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "VP8 MKV 720p30" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-VP8-MKV-720p30.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Production Max" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Production-Max.mp4"
/Users/alans/Desktop/handbrake/HandBrakeCLI -Z "Production Standard" -i "/Users/alans/Desktop/handbrake/input.mkv" -o "/Users/alans/Desktop/handbrake/output/preset-Production-Standard.mp4"
